SELECT
  id,
  email,
  password,
  role,
  created_at,
  updated_at
FROM
  kanban.users;

INSERT INTO
  kanban.users (id, email, password, role, created_at, updated_at)
VALUES
  (
    1,
    'admin.master@kanban.com',
    '$2a$12$/AmBM4Qhib21I1YQAUvga.SpFaTZQryS1LSQ5V3G6XwdDA1jjKtpe',
    'ADMIN',
    NOW(),
    NOW()
  ),
  (
    2,
    'alice.silva@kanban.com',
    '$2a$12$/AmBM4Qhib21I1YQAUvga.SpFaTZQryS1LSQ5V3G6XwdDA1jjKtpe',
    'USER',
    NOW(),
    NOW()
  ),
  (
    3,
    'bruno.mendes@kanban.com',
    '$2a$12$/AmBM4Qhib21I1YQAUvga.SpFaTZQryS1LSQ5V3G6XwdDA1jjKtpe',
    'USER',
    NOW(),
    NOW()
  ),
  (
    4,
    'carla.dias@kanban.com',
    '$2a$12$/AmBM4Qhib21I1YQAUvga.SpFaTZQryS1LSQ5V3G6XwdDA1jjKtpe',
    'USER',
    NOW(),
    NOW()
  ),
  (
    5,
    'daniel.rocha@kanban.com',
    '$2a$12$/AmBM4Qhib21I1YQAUvga.SpFaTZQryS1LSQ5V3G6XwdDA1jjKtpe',
    'USER',
    NOW(),
    NOW()
  ),
  (
    6,
    'elena.pires@kanban.com',
    '$2a$12$/AmBM4Qhib21I1YQAUvga.SpFaTZQryS1LSQ5V3G6XwdDA1jjKtpe',
    'USER',
    NOW(),
    NOW()
  ),
  (
    7,
    'felipe.souza@kanban.com',
    '$2a$12$/AmBM4Qhib21I1YQAUvga.SpFaTZQryS1LSQ5V3G6XwdDA1jjKtpe',
    'USER',
    NOW(),
    NOW()
  ),
  (
    8,
    'giovanna.neves@kanban.com',
    '$2a$12$/AmBM4Qhib21I1YQAUvga.SpFaTZQryS1LSQ5V3G6XwdDA1jjKtpe',
    'USER',
    NOW(),
    NOW()
  ),
  (
    9,
    'hugo.lima@kanban.com',
    '$2a$12$/AmBM4Qhib21I1YQAUvga.SpFaTZQryS1LSQ5V3G6XwdDA1jjKtpe',
    'USER',
    NOW(),
    NOW()
  ),
  (
    10,
    'isabela.costa@kanban.com',
    '$2a$12$/AmBM4Qhib21I1YQAUvga.SpFaTZQryS1LSQ5V3G6XwdDA1jjKtpe',
    'USER',
    NOW(),
    NOW()
  )
ON CONFLICT (id) DO NOTHING;